dist: xenial
language: python
python:
- '3.6'
- '3.7'
install:
- pip install poetry codacy-coverage
- poetry install
script:
- make -f Makefile.ci
after_success:
- python-codacy-coverage -r coverage.xml
before_deploy:
- poetry config http-basic.pypi thilp "$PYPI_PASSWORD"
deploy:
  # Main releases: tags set on master
  - provider: script
    script: poetry publish --build
    on:
      branch: master
      # We don't want to publish a release twice (once for each supported
      # python version), but we also cannot use skip_existing because
      # deployment should fail if not at least one release is published to PyPI
      # successfully. This prevents the case where someone forgot to update the
      # version number in a PR.
      python: '3.7'
env:
  global:
  - secure: duPuFLBO/bAeEnBHEQ7EHX07rLa7RO69PKH3+vTBmFVIqpZEh+X5psXTHClpFAT39AsUVvwKl5ZPwxunTOA13h6/b34M9WvArNOmMgrFvtsy2uqS9l/EJKMhhRpdL0h9Hk08Po1gJ7hEbOmFtadWtYXhge0z6bC4ykDCdKyO02sMNVceu0c+Q4j8mlV55iUjR0k9XYTRXHPyCZvhQRlWRu2SpFu+bS+i46ckdTtcLlHi0jDCAIc3od+j0ZT1CMSRdg0Bg81C9U7zCcPSpFk4AMdUjXw1h8k+7iFzzknyMDyVRi9pocPk8WXEN8i0OTGIsYCPWhgqcNP1o37xCXQj/7qPjvVYbF32vS9Ab+0RGySjlwBS19c5DoU/46IK6YR9Gpy8jmbTGbKdsK2grmg5AHs+Xv5/a5zbFoHiLRMSvqT5S8ZiAoHDKuBAQKXnHJEVYxmr1GqeOz6xPyEQlzrlbkKQlkO+D4oo3EALkq43dPo/fyKwgGVrOCyoEAfpRh/R448mVZKkuOb+IKnQCsRILpPeD8ZxQfQriVHeS4pMvZHmWA4hogZdGWe1a8xwDD2/RVclmaofyoT2HPPFgkY0wBDNlPC/RYvyXTSmAQ8XEk0CfzYh8IPsLys6v1E8MZqWG7s2xrbXQCz5jPGmmZ7MTuA20vUXGvyJCoPC6AJ/+xE=
  - secure: jbBAT/2JL7CzsTiJyeTGDoFbAfI6fpltSH7f8t+aC2xC43OcqidBRQqxWpZx8z4YYwHO2o4o91B91J62sLsv6j3oVJcK7SeOdR1pZAN3CdPMMIpi6bwjvLF7/LtbhkPuxFx2aeii+++0Cpw1mAag1chDwuXlLYbGrI6MLttlnl78i7BSGx+Sc+/PK4MQI4GFnk4+qkRfuEeP8cwsAvWThvu+d1f38HB4b96JUBFke7odJbJ0ewRcERXBRGHvigvQPqFQhJWkMKv2kf9EajFP5HzPiqhgliBJ5UlZM61z/+3dzAs+rd/82zzRy5Ny7mtYqHuDbCxJgOZ6KyPtGGMYwlqsI75P2KFAzFt9I2LCsbo1sU7Ze0UxkDbXLkFBo9MB0pG5eJ/C+SMWmEiHXCrP45my7Q5Tt7YWK43pm45byduR2iDGaB0MrraizTn9bAW3QNWHBSaksQVHE2Hx7tmsg/iihxsQHQwfjCDeIrcErCe4jLPEdUNxKSlIsd40fx0cxYP3pIo6TSJbawzLbD6WQz+4bSMz5BQD98ZHH7Wa0sb8xoDQTV1Y2C/NvnmkT7pmUmQ30A9k3r5RXILDUQAncULqU3j1PqlAH7BeLNqpEuImLkuWpqNhP96h9WXlYB4blAWWN9xLmmQKtVwM2keG6iJxm2VYm0kSr/66qWj2lvg=
