# This is a basic workflow to help you get started with Actions

name: PR

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
   uses: zalando-incubator/transformer/.github/workflows/test.yml@master
